//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Middleware {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Middleware.Properties", typeof(Properties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string DB_HOST {
            get {
                return ResourceManager.GetString("DB_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ygo/big-images.
        /// </summary>
        internal static string FULL_IMAGES_PATH {
            get {
                return ResourceManager.GetString("FULL_IMAGES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ygo/small-images.
        /// </summary>
        internal static string PREVIEW_IMAGES_PATH {
            get {
                return ResourceManager.GetString("PREVIEW_IMAGES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://storage.googleapis.com/ygoprodeck.com/pics/.
        /// </summary>
        internal static string YGO_FULL_IMAGES_URL {
            get {
                return ResourceManager.GetString("YGO_FULL_IMAGES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://storage.googleapis.com/ygoprodeck.com/pics_small/.
        /// </summary>
        internal static string YGO_PREVIEW_IMAGES_URL {
            get {
                return ResourceManager.GetString("YGO_PREVIEW_IMAGES_URL", resourceCulture);
            }
        }
    }
}
